


const carList = [
    { brand: 'Abarth' },
    { brand: 'Acura' },
    { brand: 'Alfa Romeo' },
    { brand: 'Aston Martin' },
    { brand: 'Alpine' },
    { brand: 'Audi' },
    { brand: 'Audi Sport' },
    { brand: 'Bentley' },
    { brand: 'BMW' },
    { brand: 'Bugatti' },
    { brand: 'Buick' },
    { brand: 'Cadillac' },
    { brand: 'Chevrolet' },
    { brand: 'Chrysler' },
    { brand: 'Citroën' },
    { brand: 'Dacia' },
    { brand: 'Daewoo' },
    { brand: 'Daihatsu' },
    { brand: 'Dodge' },
    { brand: 'DS' },
    { brand: 'Ferrari' },
    { brand: 'Fiat' },
    { brand: 'Ford' },
    { brand: 'Genesis' },
    { brand: 'GMC' },
    { brand: 'Honda' },
    { brand: 'Hummer' },
    { brand: 'Hyundai' },
    { brand: 'Infiniti' },
    { brand: 'Isuzu' },
    { brand: 'Jaguar' },
    { brand: 'Jeep' },
    { brand: 'Kia' },
    { brand: 'Koenigsegg' },
    { brand: 'Lamborghini' },
    { brand: 'Lancia' },
    { brand: 'Land Rover' },
    { brand: 'Lexus' },
    { brand: 'Lincoln' },
    { brand: 'Lotus' },
    { brand: 'Maserati' },
    { brand: 'Maybach' },
    { brand: 'Mazda' },
    { brand: 'McLaren' },
    { brand: 'Mercedes-Benz' },
    { brand: 'MG' },
    { brand: 'MINI' },
    { brand: 'Mitsubishi' },
    { brand: 'Nissan' },
    { brand: 'Opel' },
    { brand: 'Pagani' },
    { brand: 'Peugeot' },
    { brand: 'Porsche' },
    { brand: 'Ram' },
    { brand: 'Renault' },
    { brand: 'Rolls-Royce' },
    { brand: 'Saab' },
    { brand: 'SEAT' },
    { brand: 'Škoda' },
    { brand: 'Smart' },
    { brand: 'SsangYong' },
    { brand: 'Subaru' },
    { brand: 'Suzuki' },
    { brand: 'Tesla' },
    { brand: 'Toyota' },
    { brand: 'Vauxhall' },
    { brand: 'Volkswagen' },
    { brand: 'Volvo' }
];


export default carList;